FROM gradle:jdk17 AS build
WORKDIR /app
COPY --chown=gradle:gradle . .

ARG BUNQ_HACKATHON_OPENAI_API_KEY
ENV BUNQ_HACKATHON_OPENAI_API_KEY=${BUNQ_HACKATHON_OPENAI_API_KEY}

RUN gradle clean bootJar --no-daemon

FROM eclipse-temurin:17-jre
LABEL maintainer="bunq2025"

ARG JAR_FILE=build/libs/*.jar
COPY --from=build /app/${JAR_FILE} /app/app.jar

ARG BUNQ_HACKATHON_OPENAI_API_KEY
ENV BUNQ_HACKATHON_OPENAI_API_KEY=${BUNQ_HACKATHON_OPENAI_API_KEY}
ARG BUNQ_USER_API_KEY
ENV BUNQ_USER_API_KEY=${BUNQ_USER_API_KEY}
ARG INSTALLATION_TOKEN
ENV INSTALLATION_TOKEN=${INSTALLATION_TOKEN}

EXPOSE 8080
COPY --from=build /app/keys /app/keys
ENV BUNQ_PRIVATE_KEY_PATH=/app/keys/installation.key
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
