spring:
  config:
    import:
      - optional:dotenv:./.env
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

openai:
  api-key: ${BUNQ_HACKATHON_OPENAI_API_KEY:}
  model:
    vision: gpt-4o-mini

bunq:
  user-api-key: ${BUNQ_USER_API_KEY:}
  installation-token: ${BUNQ_INSTALLATION_TOKEN:}
  client:
    private-key-path: ${BUNQ_PRIVATE_KEY_PATH:/app/keys/installation.key}
    public-key-path:  ${BUNQ_PUBLIC_KEY_PATH:/app/keys/installation.pub}
